language: dart

dart:
  - 2.1.0
  - dev

dart_task:
  - test: -p vm,chrome
  - dartfmt
  - dartanalyzer: --fatal-infos --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
