name: dartpad_examples

environment:
  sdk: '>=2.1.0-dev.7 <3.0.0'

dev_dependencies:
  build: ^1.0.0
  build_runner: ^1.0.0
  build_web_compilers: ^0.4.4+2
  path: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.2.0
